backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: 'static/images' # Media files will be stored in the repo under images/uploads
public_folder: '/images'
publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections: # A list of collections the CMS should be able to edit
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog Posts' # Used in the UI
    label_singular: 'Blog Post' # Used in the UI, ie: "New Blog Post"
    description: >
      Create your blog post here.
    folder: content/blog
    slug: '{{slug}}' # The end of the url
    create: true
    fields: # The fields each document in this collection have
      - { name: title, label: Title, widget: string, tagname: h1 }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          dateFormat: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
        }
      - {
          name: slug,
          label: Slug,
          widget: string,
          default: '',
          hint: 'Leave blank for auto slug',
          required: false,
        }
      - {
          name: cover-image,
          label: Cover Image,
          widget: image,
          required: false,
        }
      - { name: category, label: Category, widget: hidden, default: blog }
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: 'Main content goes here.',
        }
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
    editor:
      preview: true
  - name: portfolio
    label: 'Portfolio Items'
    label_singular: 'Portfolio Item'
    description: >
      Create your portfolio item here.
    folder: content/portfolio
    slug: '{{slug}}'
    create: true
    fields:
      - { name: image, label: 'Project Image', widget: image, tagname: img }
      - { name: start, label: 'Start Year/Month', widget: string, tagname: h6 }
      - { name: end, label: 'End Year/Month', widget: string, tagname: h6 }
      - { name: technologies, label: 'Technologies Used', widget: markdown }
      - { name: goal, label: 'Project Goal', widget: markdown }
      - {
          name: project,
          label: Project Name,
          widget: string,
          tagname: h1,
          required: false,
        }
      - {
          name: link,
          label: Link to Project,
          widget: string,
          tagname: p,
          required: false,
        }
      # - {
      #     name: slug,
      #     label: Slug,
      #     widget: string,
      #     default: '',
      #     hint: 'Leave blank for auto slug',
      #     required: false,
      #   }
      - { name: category, label: Category, widget: hidden, default: portfolio }
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
    editor:
      preview: true
