backend:
  name: git-gateway
  branch: ronanc # Branch to update (optional; defaults to master)

media_folder: 'static/images' # Media files will be stored in the repo under images/uploads
public_folder: '/images'
# publish_mode: editorial_workflow

slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '-'

collections: # A list of collections the CMS should be able to edit
  - name: blog # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Blog Posts' # Used in the UI
    label_singular: 'Blog Post' # Used in the UI, ie: "New Blog Post"
    description: >
      Create your blog post here.
    folder: content/blog
    slug: '{{slug}}' # The end of the url
    create: true
    fields: # The fields each document in this collection have
      - { name: title, label: Title, widget: string, tagname: h1 }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'date',
          dateFormat: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
        }
      - {
          name: slug,
          label: Slug,
          widget: string,
          default: '',
          hint: 'Leave blank for auto slug',
          required: false,
        }
      - {
          name: discussionId,
          label: Discussion ID,
          widget: string,
          default: 2019-12-30_why-xy-or-x,
          hint: 'Must be unique (used to track comments). The comment discussion is linked to this id, if you change the id you change the discussion, and hence the comments.',
        }
      - { name: coverImage, label: Cover Image, widget: image, required: false }
      - { name: category, label: Category, widget: hidden, default: blog }
      - {
          name: tags,
          label: Social Hash Tags,
          widget: string,
          required: false,
          hint: These must be comma seperated,
        }
      - {
          name: body,
          label: Body,
          widget: markdown,
          hint: 'Main content goes here.',
        }
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
    editor:
      preview: true
  - name: portfolio
    label: 'Portfolio Items'
    label_singular: 'Portfolio Item'
    description: >
      Create your portfolio item here.
    folder: content/portfolio
    slug: '{{slug}}'
    create: true
    fields:
      - { name: title, label: Project Name, widget: string, tagname: h1 }
      - {
          name: coverImage,
          label: 'Project Image',
          widget: image,
          tagname: img,
          hint: "This image will be stretched to the full width of the portoflio list item, make sure it's wide enough, and not too tall",
        }
      - {
          label: 'Start Date',
          name: 'startDate',
          widget: 'date',
          dateFormat: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
          tagname: date,
        }
      - {
          label: 'End Date',
          name: 'endDate',
          widget: 'date',
          dateFormat: 'YYYY-MM-DD',
          format: 'YYYY-MM-DD',
          tagname: date,
        }
      - {
          name: technologiesandskills,
          label: 'Technologies Used',
          widget: markdown,
          tagname: article,
        }
      - {
          name: goal,
          label: 'Project Goals',
          widget: markdown,
          tagname: article,
        }
      - {
          name: projectLink,
          label: Link to Project,
          widget: string,
          tagname: p,
          required: false,
        }
      - {
          name: gitLink,
          label: Link to Git Source,
          widget: string,
          tagname: p,
          required: false,
        }
      - { name: category, label: Category, widget: hidden, default: portfolio }
    meta:
      - { label: 'SEO Description', name: 'description', widget: 'text' }
    editor:
      preview: true
